describe('Form Pendaftaran', () => {
  it('Isi form pendaftaran dengan salah(tidak mengisi salah satu form )', () => {
    cy.visit('https://ppdbkuini.000webhostapp.com/login')
    cy.get('#username').type('sabilajasmin')
    cy.get('#password').type('qwert')
    cy.get('.btn').click()
    cy.get('.btn').click()
    cy.get('.btn').click()
    //cy.get('#nama').type('jasmdin jksbksb')
    //cy.get('#nisn').type(23456789)
    //cy.get('#tempat_lahir').type('malang')
    //cy.get('#jenisKel').select('Laki-laki')
    //cy.get('#email').type('wakaka@gmail.com')
    cy.get('#alamat').type('malanjgghb')
    cy.get('#telp').type('0876545678')
    cy.get('#agama').select('Islam')
    cy.get('#asalSekolah').type('SMAI')
    cy.get('#jurusan').select('IPA')
    cy.get('#url_foto').selectFile({
      contents: Cypress.Buffer.from('file contents'),
      fileName: 'file.png',
      lastModified: Date.now(),
    })
    cy.get('#nama_ayah').type('samul sarifin')
    cy.get('#pekerjaan_ayah').type('wirausaha')
    cy.get('#pendidikan_ayah').type('S1 ekonomi')
    cy.get('#nama_ibu').type('imu kalsum')
    cy.get('#pekerjaan_ibu').type('ibu rumah tangga')
    cy.get('#pendidikan_ibu').type('smp')
    cy.get('.btn').click()
  })
  it('Isi form pendaftaran dengan salah(input foto dengan ekstensi .pdf )', () => {
    cy.visit('https://ppdbkuini.000webhostapp.com/login')
    cy.get('#username').type('sabilajasmin')
    cy.get('#password').type('qwert')
    cy.get('.btn').click()
    cy.get('.btn').click()
    cy.get('.btn').click()
    //cy.get('#nama').type('jasmdin jksbksb')
    //cy.get('#nisn').type(23456789)
    //cy.get('#tempat_lahir').type('malang')
    //cy.get('#jenisKel').select('Laki-laki')
    //cy.get('#email').type('wakaka@gmail.com')
    cy.get('#alamat').type('malanjgghb')
    cy.get('#telp').type('0876545678')
    cy.get('#agama').select('Islam')
    cy.get('#asalSekolah').type('SMAI')
    cy.get('#jurusan').select('IPA')
    cy.get('#url_foto').selectFile({
      contents: Cypress.Buffer.from('file contents'),
      fileName: 'file.pdf',
      lastModified: Date.now(),
    })
    cy.get('#nama_ayah').type('samul sarifin')
    cy.get('#pekerjaan_ayah').type('wirausaha')
    cy.get('#pendidikan_ayah').type('S1 ekonomi')
    cy.get('#nama_ibu').type('imu kalsum')
    cy.get('#pekerjaan_ibu').type('ibu rumah tangga')
    cy.get('#pendidikan_ibu').type('smp')
    cy.get('.btn').click()
  })
  it('verhasil mendaftar', () => {
    cy.visit('https://ppdbkuini.000webhostapp.com/login')
    cy.get('#username').type('sabilajasmin')
    cy.get('#password').type('qwert')
    cy.get('.btn').click()
    cy.get('.btn').click()
    cy.get('.btn').click()
    //cy.get('#nama').type('jasmdin jksbksb')
    //cy.get('#nisn').type(23456789)
    //cy.get('#tempat_lahir').type('malang')
    //cy.get('#jenisKel').select('Laki-laki')
    //cy.get('#email').type('wakaka@gmail.com')
    cy.get('#alamat').type('malanjgghb')
    cy.get('#telp').type('0876545678')
    cy.get('#agama').select('Islam')
    cy.get('#asalSekolah').type('SMAI')
    cy.get('#jurusan').select('IPA')
    cy.get('#url_foto').selectFile({
      contents: Cypress.Buffer.from('file contents'),
      fileName: 'file.png',
      lastModified: Date.now(),
    })
    cy.get('#nama_ayah').type('samul sarifin')
    cy.get('#pekerjaan_ayah').type('wirausaha')
    cy.get('#pendidikan_ayah').type('S1 ekonomi')
    cy.get('#nama_ibu').type('imu kalsum')
    cy.get('#pekerjaan_ibu').type('ibu rumah tangga')
    cy.get('#pendidikan_ibu').type('smp')
    cy.get('.btn').click()
  })
})